version: "3"

services:
  server:
    container_name: server_york_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/app/dev
      - exclude:/usr/app/dev/node_modules/
    env_file:
      - .env
    depends_on:
      - db_york_app
    networks:
      - app-connect
    ports:
      - "3333:3333"

  db_york_app:
    container_name: db_york_app
    image: postgres:11
    restart: unless-stopped
    volumes:
      - db_york_app-data:/data
    environment:
      POSTGRES_DB: ${DB_APP_NAME}
      POSTGRES_USER: ${DB_APP_USER}
      POSTGRES_PASSWORD: ${DB_APP_PASS}
    ports:
      - "5433:5432"
    networks:
      - app-connect

volumes:
  db_york_app-data:
  exclude:

networks:
  app-connect:
    driver: bridge
